### PR TITLE
API: fully remove mds.commands and mds.api

### PR DESCRIPTION
**Pull request by tacaswell**
Also the associated tests

### CODE REVIEW

**Comment by arkilic** [comment]
@tacaswell you need to remove `metadatastore/test/test_commands.py`

**Comment by tacaswell** [comment]
No, I trimmed it down to only the useful tests

**Comment by arkilic** [comment]
Travis unhappy about some of them:

```
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw0] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw1] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw2] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw3] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw4] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw5] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw6] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw7] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw8] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw9] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw10] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw11] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_starts-kw12] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_stops-kw13] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_stops-kw14] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_stops-kw15] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_stops-kw16] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_stops-kw17] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_stops-kw18] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_stops-kw19] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_run_stops-kw20] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_descriptors-kw21] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_descriptors-kw22] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_descriptors-kw23] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_descriptors-kw24] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_descriptors-kw25] ERROR
metadatastore/test/test_commands.py::test_find_funcs_for_smoke[1-find_descriptors-kw26] ERROR
```

**Comment by arkilic** [comment]
👍 You commit faster than your own shadow @tacaswell

**Comment by tacaswell** [comment]
I am not stoked about having to use auth in the tests.  I would rather run the fixtures without auth and then have an extra test on travis that just does a smoke test with auth.

**Comment by arkilic** [comment]
Since all our mongo shells will have to use the auth, I think we should also test against auth.

**Comment by tacaswell** [comment]
I added an env to make it opt-in, travis can run auth, I can run with out :wink:

**Comment by arkilic** [comment]
I like that very much

**Pull request merged**
